# Generated by Django 3.2.4 on 2022-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=191)),
                ('price', models.TextField(default='', editable=False, max_length=50)),
            ],
        ),
    ]
